#!/bin/bash
#PBS -l walltime=168:00:00,select=1:ncpus=32:mpiprocs=32:mem=64gb
#PBS -A st-ssrebnik-1
#PBS -N MAK
#PBS -o out.txt
#PBS -e err.txt
#PBS -m abe
#PBS -M miladasgarpour@gmail.com

module load gcc/7.5.0
module load python/3.7.10
module load openmpi

cd $PBS_O_WORKDIR # here in scratch write everything

echo Job ID: >> job.info
echo $PBS_JOBID >> job.info
echo Job name: >> job.info
echo $PBS_JOBNAME >> job.info

mpirun -n 32 ../../lammps/src/lmp_mpi -in *.lmps

# End of file 
